config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'devise/passwords#update'
  end
 

  
  resources :shifts, only: [:show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/organisations/:id/join', to: 'organisations#join'
  put '/organisations/:id/join', to: 'organisations#join', as: 'join_organisation'
  get '/organisations/:id/leave', to: 'organisations#leave'
  put '/organisations/:id/leave', to: 'organisations#leave', as: 'leave_organisation'
  resources :organisations, except: :destroy

  get '/home', to: 'home#index', as: 'home'
  root to: "home#index"
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all

    @userOrganisation = Organisation.where(id: current_user.organisation_id).first
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  def join
    @user = User.find_by(id: current_user.id)

    if (@user.organisation_id.to_i != params[:id].to_i) #Prevents user from rejoining the organisation they're already a member of
      if @user.update(user_params)
        @user.update(organisation_id: params[:id])
      end
    end 

    

    redirect_to :root
  end



  def leave
    @user = User.find_by(id: current_user.id)

    
    if @user.organisation_id.to_i == params[:id].to_i # Users can only leave an organisation that they are a member of
      if @user.update(user_params)
        @user.update(organisation_id: nil)
      end
    end

    redirect_to :root
  end


  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1
  # PATCH/PUT /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to organisations_url, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.permit(:organisation_id)
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisation_params
      params.require(:organisation).permit(:name, :hourly_rate)
    end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.erb
<%= form_with(model: organisation, local: true) do |form| %>
  <% if organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% organisation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hourly_rate %>
    <span>$<%= form.text_field :hourly_rate %></span>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back to List', organisations_path %> |
<%= link_to 'Back to Home', root_path %>

app/views/organisations/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Existing Organisations</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hourly rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
        <td><%= organisation.name %></td>
        <td><%= organisation.hourly_rate %></td>
        <td><%= link_to 'Show', organisation %></td>
        <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
        
        <% if (@userOrganisation.nil?) || !(organisation.id == @userOrganisation.id) %>
          <td><%= link_to 'Join', join_organisation_path(organisation), method: :put %></td>
        <% else %>
          <td><strong>(Your current organisation)</strong></td>
          <td><%= link_to 'Leave', leave_organisation_path(organisation), method: :put %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Create New Organisation</h2>
<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<h1>New Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<p>
  <strong>Hourly rate:</strong>
  <%= @organisation.hourly_rate %>
</p>

<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back to List', organisations_path %> |
<%= link_to 'Back to Home', root_path %>