config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'devise/passwords#update'
  end
 

  
  resources :shifts, only: [:show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/organisations/:id/join', to: 'organisations#join'
  put '/organisations/:id/join', to: 'organisations#join', as: 'join_organisation'
  get '/organisations/:id/leave', to: 'organisations#leave'
  put '/organisations/:id/leave', to: 'organisations#leave', as: 'leave_organisation'
  resources :organisations, except: :destroy

  get '/home', to: 'home#index', as: 'home'
  root to: "home#index"
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :User, optional: true

  validate :validate_user_id, if: :user_id?

  private

  # Ensures that the user_id in the Shifts table actually exists in the User table
  def validate_user_id
    errors.add(:user_id, "is invalid") unless User.exists?(self.user_id)
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)
    
    if (user_signed_in?)
      @shift.user_id = current_user.id
    end

    if @shift.break_length.nil?
      @shift.break_length = 0
    end

    if (@shift.finish < @shift.start)

      respond_to do |format|
          format.html { redirect_to root_path, alert: 'Shift FINISH date and time can\'t be BEFORE the START date and time' }
          format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    elsif (((Time.parse(@shift.finish.to_s).to_time - Time.parse(@shift.start.to_s).to_time) / 3600) - (@shift.break_length.to_d / 60)) < 0
      respond_to do |format|
        format.html { redirect_to root_path, alert: 'Break time cannot be larger than the difference of the shift start and finish date and times' }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        if @shift.save
          format.html { redirect_to root_path, notice: 'Shift was successfully created.' }
          #format.json { render :show, status: :created, location: @shift }
        else
          format.html { render :new }
          format.json { render json: @shift.errors, status: :unprocessable_entity }
        end
      end
    end

 
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:start, :finish, :break_length)
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_with(model: shift, local: true) do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% else %>
    <h1>New Shift Created!</h1>
  <% end %>

<% end %>

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shifts</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>Finish</th>
      <th>Break length</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.start %></td>
        <td><%= shift.finish %></td>
        <td><%= shift.break_length %></td>
        <td><%= shift.User %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<%= render 'form', shift: @shift %>

<%= link_to 'Back', root_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @shift.start %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @shift.finish %>
</p>

<p>
  <strong>Break length:</strong>
  <%= @shift.break_length %>
</p>

<p>
  <strong>User:</strong>
  <%= @shift.User %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>