config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'devise/passwords#update'
  end
 

  
  resources :shifts, only: [:show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/organisations/:id/join', to: 'organisations#join'
  put '/organisations/:id/join', to: 'organisations#join', as: 'join_organisation'
  get '/organisations/:id/leave', to: 'organisations#leave'
  put '/organisations/:id/leave', to: 'organisations#leave', as: 'leave_organisation'
  resources :organisations, except: :destroy

  get '/home', to: 'home#index', as: 'home'
  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TandaChalRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <h1><a href="<%= home_path %>"> Adnat</a></h1>
          <div>

        <% if user_signed_in?%>

            <h3><%= link_to "Logout", destroy_user_session_path, method: :delete %></h3>


            <h3><%= link_to "Account Settings", edit_user_registration_path %></h3>


        <% else%>

            

            <h3><%= link_to 'Login', new_user_session_path %></h3>


            <h3><%= link_to 'Register', new_user_registration_path %></h3>

        <% end %>
      </div>

    <h3 style="color: green"><%= notice %></h3>
    <h3 style="color: red"><%= alert %></h3>

    <% if user_signed_in?%>
      <p>Logged in as <%= current_user.name %></p>
    <% end %>
    <%= yield %>
  </body>
</html>